expiration:
  evaluation:
    rate:
      # Check types: PERCENT, COUNT
      type: PERCENT
      value: 4.35
    random: false
  days_per_area:
    250000: -1
    10000: 90
    100: 60
    0: 30
  bypass:
    claim_blocks: 10000
    bonus_claim_blocks: -1
    permissions:
      - gpclaimexpiration.persist
  # Command placeholders: $ownerName, $ownerId, $world, $locX, $locY, $locZ
  # Additional claim command placeholders: $claimId, $locXMax, $locYMax, $locZMax, $area, $width (X), $depth (Z)
  claim.commands: []
  pet:
    days: 60
    commands: []

# Per-world overrides
# Note that only certain values are configurable per-world.
overrides:
  # Ex.: A high turnover world may have higher activity requirements.
  high_turnover_world:
    expiration:
      days-per-area:
        250000: -1
        10000: 7
        0: 2
      pet:
        days: 7
  # Ex.: The commercial hub requires activity to keep store location, no one is allowed to bypass expiration.
  commercial_hub_world:
    expiration:
      bypass:
        claim_blocks: -1
        bonus_claim_blocks: -1
        permissions: []
      claim.commands:
      - adminclaimauction $world $locX $locZ $locXMax $locZMax $area
